"""Stable domain values. Database columns use validated strings for provider extensibility."""

from enum import StrEnum


class ExamAttemptState(StrEnum):
    CREATED = "CREATED"
    READY = "READY"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    FINALIZED = "FINALIZED"
    ABANDONED = "ABANDONED"


class AttemptItemState(StrEnum):
    PENDING = "PENDING"
    PRESENTING = "PRESENTING"
    WAITING_FOR_ANSWER = "WAITING_FOR_ANSWER"
    ASR_PROCESSING = "ASR_PROCESSING"
    ANSWER_ANALYZING = "ANSWER_ANALYZING"
    FOLLOW_UP_PENDING = "FOLLOW_UP_PENDING"
    WAITING_FOR_FOLLOW_UP = "WAITING_FOR_FOLLOW_UP"
    FINAL_ASSESSING = "FINAL_ASSESSING"
    FINALIZED = "FINALIZED"
    NEEDS_ATTENTION = "NEEDS_ATTENTION"


class EvaluationMode(StrEnum):
    COVERAGE = "COVERAGE"
    QUALITY_RISK = "QUALITY_RISK"


class AnswerType(StrEnum):
    MAIN = "MAIN"
    FOLLOW_UP = "FOLLOW_UP"
    RE_RECORDING = "RE_RECORDING"


class CriticalErrorResult(StrEnum):
    NOT_TRIGGERED = "NOT_TRIGGERED"
    TRIGGERED = "TRIGGERED"
    UNCERTAIN = "UNCERTAIN"
    CONFLICTED = "CONFLICTED"
    OVERRIDDEN_BY_HUMAN = "OVERRIDDEN_BY_HUMAN"


class LLMQualificationStatus(StrEnum):
    UNTESTED = "UNTESTED"
    QUALIFYING = "QUALIFYING"
    QUALIFIED = "QUALIFIED"
    CONDITIONAL = "CONDITIONAL"
    FAILED = "FAILED"
    RETIRED = "RETIRED"


class TaskJobType(StrEnum):
    ASR = "ASR"
    TTS = "TTS"
    COVERAGE = "COVERAGE"
    CRITICAL_ERROR = "CRITICAL_ERROR"
    QUALITY_RISK = "QUALITY_RISK"
    FOLLOW_UP = "FOLLOW_UP"
    FINAL_ASSESSMENT = "FINAL_ASSESSMENT"


class TaskJobState(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
